# Generated by Django 4.2.6 on 2023-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_product_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
