# Generated by Django 4.2.6 on 2023-10-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_product',
            name='product_rate',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
