# Generated by Django 4.2.6 on 2023-10-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0002_buy_product_product_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='client',
        ),
    ]
