# Generated by Django 4.2.6 on 2023-10-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0003_remove_buy_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
