# Generated by Django 4.2.6 on 2023-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeorders', '0004_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy_product',
            options={'verbose_name': 'Купленный продукт', 'verbose_name_plural': 'Купленные продукты'},
        ),
        migrations.AlterField(
            model_name='buy_product',
            name='product_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
