# Generated by Django 4.2.6 on 2023-10-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makeorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Шаг',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Buy_Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_date_beg', models.DateTimeField(auto_now_add=True)),
                ('step_date_end', models.DateTimeField(auto_now_add=True)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_step_buy', to='makeorders.buy')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_step_step', to='deals.step')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-step_date_beg',),
            },
        ),
    ]
