# Generated by Django 4.2.6 on 2023-10-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Проданный товар',
                'verbose_name_plural': 'Проданные товары',
            },
        ),
        migrations.AlterField(
            model_name='buy_step',
            name='step_date_beg',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='buy_step',
            name='step_date_end',
            field=models.DateTimeField(),
        ),
    ]
